import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { paytone } from "./ui/fonts";
import Navbar from "./ui/components/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={paytone.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
